name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22
    
    - name: Run all tests
      run: make test-all
    
    - name: Build for all platforms
      run: make build-all
    
    - name: Create release archives
      run: |
        cd bin
        tar -czf deltagram-linux-amd64.tar.gz deltagram-linux-amd64
        tar -czf deltagram-linux-arm64.tar.gz deltagram-linux-arm64
        tar -czf deltagram-darwin-amd64.tar.gz deltagram-darwin-amd64
        tar -czf deltagram-darwin-arm64.tar.gz deltagram-darwin-arm64
        zip deltagram-windows-amd64.zip deltagram-windows-amd64.exe
    
    - name: Generate changelog
      id: changelog
      run: |
        # Simple changelog generation
        echo "## Changes" > CHANGELOG.md
        git log --oneline --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD~1)..HEAD >> CHANGELOG.md || echo "- Initial release" >> CHANGELOG.md
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        cat CHANGELOG.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/deltagram-linux-amd64.tar.gz
          bin/deltagram-linux-arm64.tar.gz
          bin/deltagram-darwin-amd64.tar.gz
          bin/deltagram-darwin-arm64.tar.gz
          bin/deltagram-windows-amd64.zip
        body: ${{ steps.changelog.outputs.CHANGELOG }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}